# Generated by Django 4.2.30 on 2026-08-23 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='bim_models/')),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('file_format', models.CharField(choices=[('ifc', 'IFC'), ('rvt', 'Revit'), ('nwd', 'Navisworks'), ('other', 'Other')], max_length=50)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_bim_models', to='projects.project')),
            ],
        ),
    ]
