# Generated by Django 4.2.30 on 2026-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_bimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, default='', help_text='Primary client contact name or email', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', help_text='Name of the client / commissioning body', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Project site latitude', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Project site longitude', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, default='', help_text='Internal or contract project reference number', max_length=100),
        ),
    ]
