# Generated by Django 4.2.30 on 2026-09-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_district_profile_is_state_hq_profile_district'),
        ('projects', '0004_project_client_contact_project_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.ForeignKey(blank=True, help_text='District office with jurisdiction over this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='government.district'),
        ),
    ]
