# Generated by Django 4.2.30 on 2026-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cold_storage',
            field=models.BooleanField(db_index=True, default=False, help_text='Project moved to cold storage after a prolonged period without activity (all records remain intact and directly accessible)'),
        ),
        migrations.AddField(
            model_name='project',
            name='cold_stored_at',
            field=models.DateTimeField(blank=True, help_text='When the project was moved to cold storage', null=True),
        ),
    ]
