# Generated by Django 4.2.30 on 2026-09-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_cold_storage_project_cold_stored_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
