# Generated by Django 5.2 on 2026-09-17 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_boundary_remove_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Site check-in radius in metres. Null means this project has not recorded one and the platform default applies (DEFAULT_GEOFENCE_RADIUS_M). Deliberately not defaulted to 50: that is a platform policy, not an attribute of this project, and a column default would make every existing row claim a geofence nobody entered.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
