# Generated by Django 5.2 on 2026-09-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_geofence_radius_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_inspector_user',
            field=models.ForeignKey(blank=True, help_text='The inspector assigned to this project. This is what grants access; `assigned_inspector` mirrors the name for display only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
