# Generated by Django 4.2.30 on 2026-10-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_coordinate_system_project_corner_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coordinate_system',
        ),
        migrations.RemoveField(
            model_name='project',
            name='corner_coordinates',
        ),
    ]
