# Generated by Django 4.2.30 on 2026-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundittest',
            name='test_location',
            field=models.CharField(blank=True, default='', help_text='On-site location of the test station, e.g. Grid D-7 Core Section', max_length=255),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='transducer_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct Transmission'), ('semi_direct', 'Semi-Direct Transmission'), ('indirect', 'Indirect (Surface) Transmission')], default='', help_text='Transducer coupling arrangement (BS 1881-203)', max_length=20),
        ),
    ]
