# Generated by Django 5.2 on 2026-09-04 09:04

import apps.digital_eye.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0002_alter_pundittest_options_and_more'),
        ('projects', '0005_project_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebarTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_reference', models.CharField(default=apps.digital_eye.models.generate_test_ref, max_length=40, unique=True)),
                ('structural_element', models.CharField(blank=True, default='Column', max_length=200)),
                ('test_location', models.CharField(blank=True, default='Ground Floor', max_length=200)),
                ('main_bar_mm', models.FloatField(blank=True, help_text='Estimated main bar diameter in mm', null=True)),
                ('links_mm', models.FloatField(blank=True, help_text='Estimated link/stirrup diameter in mm', null=True)),
                ('spacing_mm', models.CharField(blank=True, default='', help_text="Spacing of bars/links (can be numeric or '-' if unknown)", max_length=50)),
                ('cover_depth_mm', models.FloatField(blank=True, help_text='Measured concrete cover depth over rebar in mm', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebar_tests', to='digital_eye.fielddevice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebar_tests', to='projects.project')),
            ],
        ),
    ]
