# Generated by Claude Code 2026-09-04

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0003_rebartest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMModelGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(blank=True, default='', help_text='Original uploaded file name', max_length=255)),
                ('translated_from_rvt', models.BooleanField(default=False)),
                ('element_count', models.IntegerField(default=0)),
                ('elements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_model_geometry_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bim_model_geometry', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'BIM model geometries',
            },
        ),
    ]
