# Generated by Django 4.2.30 on 2026-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0004_bimmodelgeometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereportrecord',
            name='certified_engineer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='compliance_status',
            field=models.CharField(default='NOT_ASSESSED', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='generated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
