# Generated by Django 4.2.30 on 2026-09-04 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0005_alter_devicereportrecord_certified_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundittest',
            name='floor',
            field=models.CharField(blank=True, default='', help_text="Floor/level of the test station, e.g. 'Ground Floor', 'First Floor'", max_length=100),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='weather_condition',
            field=models.CharField(blank=True, default='', help_text='Weather condition at test time, recorded by the operator on site', max_length=150),
        ),
        migrations.CreateModel(
            name='PUNDITReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_label', models.CharField(help_text="Test point on the element: 'A', 'B', 'C', ... (A is the first point)", max_length=10)),
                ('path_length_mm', models.FloatField(blank=True, help_text="Transducer path length shared by the element's points", null=True)),
                ('transit_time_us', models.FloatField(help_text='The measured transit time at this point')),
                ('velocity_km_s', models.FloatField(blank=True, help_text='Computed v = L/t (read-only; never operator-entered)', null=True)),
                ('ecs_mpa', models.FloatField(blank=True, help_text='Computed E.C.S from the platform calibration curve (read-only)', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='digital_eye.pundittest')),
            ],
            options={
                'ordering': ['point_label'],
            },
        ),
        migrations.AddConstraint(
            model_name='punditreading',
            constraint=models.UniqueConstraint(fields=('test', 'point_label'), name='uniq_reading_point_per_test'),
        ),
    ]
