# Generated by Django 4.2.30 on 2026-09-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_district'),
        ('digital_eye', '0006_pundittest_floor_pundittest_weather_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatafile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_files', to='projects.project'),
        ),
    ]
