# Generated by Django 4.2.30 on 2026-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0007_sensordatafile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='punditreading',
            name='crack_depth_mm',
            field=models.FloatField(blank=True, help_text='Computed time-difference crack depth at this point (read-only)', null=True),
        ),
        migrations.AddField(
            model_name='punditreading',
            name='surface_condition',
            field=models.CharField(blank=True, default='', help_text='Surface-quality method only: the condition observed at this point', max_length=150),
        ),
        migrations.AddField(
            model_name='punditreading',
            name='uncracked_transit_time_us',
            field=models.FloatField(blank=True, help_text='Crack-depth method only: the uncracked-path transit time t_0 measured at this point', null=True),
        ),
        migrations.AlterField(
            model_name='punditreading',
            name='transit_time_us',
            field=models.FloatField(blank=True, help_text='The measured transit time at this point (t for pulse velocity, t_cracked for crack depth; not measured for surface quality)', null=True),
        ),
    ]
