# Generated by Django 4.2.30 on 2026-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0008_punditreading_crack_depth_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatafile',
            name='file_type',
            field=models.CharField(choices=[('gpr_radargram', 'GPR Radargram'), ('gpr_depth_slice', 'GPR Depth Slice'), ('gpr_raw', 'GPR Raw Dataset'), ('pundit_raw', 'PUNDIT Raw Export'), ('gnss_rinex', 'GNSS RINEX Log'), ('bim_model', 'BIM Model File (.ifc / .rvt, kept for re-import)'), ('photo', 'Site Photo'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
