# Generated by Django 4.2.30 on 2026-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0009_alter_sensordatafile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundittest',
            name='concrete_age_days',
            field=models.PositiveIntegerField(blank=True, help_text='Concrete age at test time in days (optional; strength gain past 28 days is minimal, so ages beyond 28 are informative rather than corrective)', null=True),
        ),
    ]
