# Generated by Django 4.2.30 on 2026-09-10 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


DEFAULT_CURVE_NAME = 'Platform default (laboratory linear)'


def seed_default_curve(apps, schema_editor):
    """
    Seed the single platform-wide fallback curve: the documented laboratory
    linear calibration f_cu = 8.961*V(km/s) - 7.97, expressed in the m/s
    curve-parameter domain. No fabricated exponential/polynomial/SonReb
    curves are seeded — those must be fitted from real calibration data
    via the Nexucon Link regression engine.
    """
    StrengthCurve = apps.get_model('digital_eye', 'StrengthCurve')
    if StrengthCurve.objects.filter(is_default=True).exists():
        return
    StrengthCurve.objects.create(
        name=DEFAULT_CURVE_NAME,
        curve_type='linear',
        standard='Nexucon laboratory calibration (documented)',
        velocity_unit='m/s',
        strength_unit='MPa',
        formula_params={'m': 0.008961, 'c': -7.97},
        valid_range_min_ms=2000.0,
        valid_range_max_ms=5000.0,
        is_default=True,
        provenance={
            'source': 'apps.reports.ndt_reports.ECS_SLOPE/ECS_INTERCEPT',
            'reference': 'Documented laboratory linear calibration '
                         'f_cu = 8.961*V(km/s) - 7.97, valid 2.0-5.0 km/s',
            'note': 'Seeded from the platform\'s pre-existing documented '
                    'calibration; mathematically identical to the legacy '
                    'fixed formula.',
        },
    )


def unseed_default_curve(apps, schema_editor):
    StrengthCurve = apps.get_model('digital_eye', 'StrengthCurve')
    StrengthCurve.objects.filter(name=DEFAULT_CURVE_NAME,
                                 is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_project_district'),
        ('digital_eye', '0010_pundittest_concrete_age_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='punditreading',
            name='rebound_number',
            field=models.FloatField(blank=True, help_text="Rebound hammer reading at this point (required only when the project's active curve is a SonReb combination curve)", null=True),
        ),
        migrations.AddField(
            model_name='punditreading',
            name='strength_curve_snapshot',
            field=models.JSONField(blank=True, help_text="Provenance of the curve that produced this point's E.C.S (Nexucon Link)", null=True),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='rebound_number',
            field=models.FloatField(blank=True, help_text='Rebound hammer reading for this element (shared by its points unless a reading carries its own; required only for SonReb curves)', null=True),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='strength_curve_snapshot',
            field=models.JSONField(blank=True, help_text='Provenance of the curve that produced the element-mean E.C.S: curve id/name/type/formula/valid range (Nexucon Link)', null=True),
        ),
        migrations.AlterField(
            model_name='punditreading',
            name='ecs_mpa',
            field=models.FloatField(blank=True, help_text="Computed E.C.S from the project's active calibration curve (read-only)", null=True),
        ),
        migrations.CreateModel(
            name='StrengthCurve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('curve_type', models.CharField(choices=[('linear', 'Linear: f = m*V + c'), ('polynomial', 'Polynomial (deg 2): f = c0 + c1*V + c2*V^2'), ('exponential', 'Exponential: f = a*exp(b*V) + c'), ('sonreb', 'SonReb (UPV + rebound): f = a*V^b*R^c'), ('lookup', 'Lookup table (piecewise-linear interpolation)')], max_length=20)),
                ('standard', models.CharField(blank=True, default='', help_text="Reference standard, e.g. 'BS 1881-203:1999', 'ACI 228.2R-2018'", max_length=100)),
                ('velocity_unit', models.CharField(default='m/s', max_length=20)),
                ('strength_unit', models.CharField(default='MPa', max_length=20)),
                ('formula_params', models.JSONField(default=dict, help_text="Curve parameters in the m/s velocity domain, e.g. {'m': 0.008961, 'c': -7.97} / {'a':..., 'b':..., 'c':...} / {'coeffs': [c0, c1, c2]} / {'points': [{'v', 'f'}, ...]}")),
                ('data_points', models.JSONField(blank=True, default=list, help_text="The real calibration pairs the curve was fitted from: [{'v' (m/s), 'f' (MPa), 'r' (rebound, optional)}, ...]")),
                ('valid_range_min_ms', models.FloatField(blank=True, help_text='Calibrated range lower bound (m/s)', null=True)),
                ('valid_range_max_ms', models.FloatField(blank=True, help_text='Calibrated range upper bound (m/s)', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='Coefficient of determination (regression-derived curves)', null=True)),
                ('standard_error', models.FloatField(blank=True, null=True)),
                ('aic', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one platform-wide fallback curve should carry this')),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='How the curve was established: source, reference, operator')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strength_curves_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strength_curves', to='projects.project')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCurveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_curve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_projects', to='digital_eye.strengthcurve')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curve_setting', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curve_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_default_curve, unseed_default_curve),
    ]
