# Generated by Django 4.2.30 on 2026-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0011_punditreading_rebound_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='analysis_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='anomalies_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='compliance_check_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='critical_defects_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='overall_health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='scan_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='total_elements_scanned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimstructuralelement',
            name='designed_concrete_grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bimstructuralelement',
            name='designed_cover_depth_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimstructuralelement',
            name='designed_rebar_spacing_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimstructuralelement',
            name='gpr_clearance_status',
            field=models.CharField(blank=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='bimstructuralelement',
            name='pundit_clearance_status',
            field=models.CharField(blank=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicereportrecord',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitaleyefinding',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitaleyefinding',
            name='severity',
            field=models.CharField(blank=True, default='MEDIUM', max_length=50),
        ),
        migrations.AlterField(
            model_name='digitaleyefinding',
            name='taxonomy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='accuracy_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='deviation_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='elevation_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='layer_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencespatialpoint',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='antenna_frequency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='dielectric_constant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='dielectric_permittivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='grid_axis',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='max_penetration_depth_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='measured_cover_depth_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='measured_rebar_spacing_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='radargram_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='specified_rebar_spacing_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='status',
            field=models.CharField(blank=True, default='RECORDED', max_length=50),
        ),
        migrations.AlterField(
            model_name='gprscan',
            name='transect_length_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='file_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='node_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='stage',
            field=models.CharField(blank=True, default='QUEUED', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingqueuejob',
            name='total_bytes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pundittest',
            name='concrete_quality_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pundittest',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pundittest',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pundittest',
            name='status',
            field=models.CharField(blank=True, default='RECORDED', max_length=50),
        ),
    ]
