# Generated by Django 4.2.30 on 2026-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0012_alter_aianalysisrecord_analysis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebartest',
            name='structural_element',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rebartest',
            name='test_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='bcf_topics_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='synced_elements_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='synced_models_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='trimble_project_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='trimble_project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trimbleconnection',
            name='webhook_active',
            field=models.BooleanField(default=False),
        ),
    ]
