# Generated by Django 4.2.30 on 2026-09-13 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_remove_project_boundary_remove_project_location'),
        ('digital_eye', '0014_strengthcurve_derived_fit_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structural_element', models.CharField(blank=True, default='', help_text='Element the core was taken from, e.g. COL-C24', max_length=100)),
                ('test_location', models.CharField(blank=True, default='', help_text='Where on site the core was extracted', max_length=255)),
                ('core_diameter_mm', models.FloatField(blank=True, help_text='Core diameter in mm (e.g. 100)', null=True)),
                ('core_length_mm', models.FloatField(blank=True, help_text='Core length after trimming, in mm', null=True)),
                ('lab_strength_mpa', models.FloatField(blank=True, help_text='Compressive strength from the laboratory crushing test (MPa) — typed from the test certificate, never estimated', null=True)),
                ('lab_report_ref', models.CharField(blank=True, default='', help_text='Laboratory test-certificate reference', max_length=150)),
                ('sampled_at', models.DateTimeField(blank=True, help_text='When the core was extracted on site', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_samples', to='projects.project')),
                ('pundit_test', models.ForeignKey(blank=True, help_text='The in-situ UPV test at/near the core location — its measured velocity pairs with the laboratory strength', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_samples', to='digital_eye.pundittest')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_samples_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
