# Generated by Django 5.2 on 2026-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0016_punditanalysisreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundittest',
            name='ai_ci_lower_mpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='ai_ci_upper_mpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='ai_data_quality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='ai_pof_pct',
            field=models.FloatField(blank=True, help_text='Probability of failure against design strength', null=True),
        ),
        migrations.AddField(
            model_name='pundittest',
            name='ai_reasoning_traces',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
