# Generated by Django 4.2.30 on 2026-09-16 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital_eye', '0017_pundittest_ai_ci_lower_mpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthcurve',
            name='se_adjustment_factor',
            field=models.FloatField(default=1.0, help_text='k — the confidence factor for the confidence-margin method (1.0 ~ 84% one-sided, 1.645 ~ 95% one-sided). Unused by the other methods.'),
        ),
        migrations.AddField(
            model_name='strengthcurve',
            name='se_adjustment_method',
            field=models.CharField(choices=[('none', 'No adjustment — report the curve estimate as fitted'), ('bias_correction', 'Bias correction — add the measured mean residual (the "+2" gap-closing convention, computed from real pairs)'), ('confidence_margin', 'Confidence margin — subtract k x standard error (conservative characteristic strength, BS EN 13791 logic)')], default='none', help_text="How the curve's standard error is factored into the reported f_cu. 'none' until deliberately enabled.", max_length=30),
        ),
        migrations.CreateModel(
            name='NexuconLinkSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('preferred_curve_type', models.CharField(choices=[('linear', 'Linear: f = m*V + c'), ('polynomial', 'Polynomial (deg 2): f = c0 + c1*V + c2*V^2'), ('exponential', 'Exponential: f = a*exp(b*V) + c'), ('sonreb', 'SonReb (UPV + rebound): f = a*V^b*R^c'), ('lookup', 'Lookup table (piecewise-linear interpolation)')], default='exponential', help_text='The curve type the calibration workflow pre-selects and recommends. Concrete behaviour is non-linear, so the default is exponential per the 15 Sep 2026 direction. This does not activate any curve by itself.', max_length=20)),
                ('default_standard', models.CharField(blank=True, default='BS 1881-203:1986', help_text='Standard the new curves are recorded against by default.', max_length=100)),
                ('velocity_unit', models.CharField(default='m/s', max_length=20)),
                ('strength_unit', models.CharField(default='MPa', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nexucon_link_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nexucon Link system settings',
                'verbose_name_plural': 'Nexucon Link system settings',
            },
        ),
    ]
