# Generated by Django 4.2.30 on 2026-09-30 14:09

import apps.digital_eye.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0005_alter_finding_title'),
        ('projects', '0007_remove_project_boundary_remove_project_location'),
        ('digital_eye', '0018_strengthcurve_se_adjustment_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunditScanBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(help_text="Human-readable folder/session name, e.g. 'Floor 2 RC Slab - Primary Grid (48 Elements)'", max_length=255)),
                ('batch_reference', models.CharField(db_index=True, default=apps.digital_eye.models.generate_batch_ref, help_text="Deterministic batch code, e.g. 'BATCH-2026-09-048'", max_length=64, unique=True)),
                ('inspector_name', models.CharField(blank=True, default='', max_length=255)),
                ('device_name', models.CharField(blank=True, default='Screening Eagle Pundit Live', max_length=128)),
                ('device_serial', models.CharField(blank=True, default='', max_length=128)),
                ('element_count', models.PositiveIntegerField(default=0, help_text='Verified count of structural elements tested in this batch (e.g. 48).')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when testing was conducted on site.')),
                ('status', models.CharField(choices=[('RAW_INGESTED', 'Raw Data Ingested (Awaiting Calibration)'), ('CALIBRATED', 'Calibrated (Ready for Analysis)'), ('ANALYSIS_COMPLETE', 'Analysis Completed')], db_index=True, default='RAW_INGESTED', max_length=32)),
                ('floor', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pundit_batches_conducted', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pundit_scan_batches', to='projects.project')),
                ('raw_sensor_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pundit_batches', to='digital_eye.sensordatafile')),
            ],
            options={
                'verbose_name': 'PUNDIT Scan Batch',
                'verbose_name_plural': 'PUNDIT Scan Batches',
                'ordering': ['-scan_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structural_element', models.CharField(help_text="e.g. 'Column C24', 'Drop Beam B12'", max_length=255)),
                ('grid_location', models.CharField(blank=True, default='', max_length=128)),
                ('floor', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(choices=[('honeycombing', 'Honeycombing / Voiding'), ('cracking', 'Cracking (Shear / Flexure / Thermal)'), ('spalling', 'Spalling & Delamination'), ('rebar_exposure', 'Exposed Rebar / Low Cover'), ('moisture_ingress', 'Moisture Ingress / Dampness'), ('efflorescence', 'Efflorescence / Leaching'), ('sound_uniform', 'Sound & Uniform Concrete'), ('other', 'Other Workmanship Defect')], default='honeycombing', max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High (Structural Concern)'), ('CRITICAL', 'Critical (Stop Work / Urgent Remediation)')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(help_text='Detailed defect dimensions and observations.')),
                ('inspector_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_observations', to='digital_eye.punditscanbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_observations', to='inspections.inspection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_observations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Visual Observation',
                'verbose_name_plural': 'Visual Observations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualObservationPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='visual_observations/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sha256_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='digital_eye.visualobservation')),
            ],
            options={
                'verbose_name': 'Visual Observation Photo',
                'verbose_name_plural': 'Visual Observation Photos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendee_name', models.CharField(max_length=255)),
                ('organization', models.CharField(help_text="e.g. 'ExxonMobil', 'Julius Berger', 'LASBCA'", max_length=255)),
                ('role', models.CharField(choices=[('Client Representative', 'Client Representative'), ('Resident Structural Engineer', 'Resident Structural Engineer'), ('Contractor QA/QC Manager', 'Contractor QA/QC Manager'), ('Government / LASBCA Inspector', 'Government / LASBCA Inspector'), ('Project Director', 'Project Director'), ('Site Safety Officer', 'Site Safety Officer'), ('Other', 'Other Witness')], default='Client Representative', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('signed_off', models.BooleanField(default=True)),
                ('signature_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='digital_eye.punditscanbatch')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='inspections.inspection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_attendance_records', to='projects.project')),
            ],
            options={
                'verbose_name': 'Site Attendance Record',
                'verbose_name_plural': 'Site Attendance Records',
                'ordering': ['arrival_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('curve_type', models.CharField(choices=[('exponential', 'Exponential (Default Non-Linear)'), ('polynomial', 'Polynomial (Degree 2)'), ('sonreb', 'SonReb Combined (UPV + Rebound)'), ('linear', 'Linear (Not Recommended)'), ('lookup', 'Lookup Table Interpolation')], default='exponential', max_length=32)),
                ('params', models.JSONField(default=dict, help_text="Model coefficients, e.g. {'a': 1.20, 'b': 0.85, 'c': 0.0}")),
                ('design_strength_mpa', models.FloatField(default=25.0, help_text='Statutory or design target strength in MPa (e.g. 25.0 for C25/30).')),
                ('cube_correlation_data', models.JSONField(blank=True, default=list, help_text="Optional array of [{'velocity_ms': 3800, 'cube_strength_mpa': 29.8}] pairs.")),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibration_profiles', to='digital_eye.punditscanbatch')),
                ('calibrated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_performed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_profiles', to='projects.project')),
            ],
            options={
                'verbose_name': 'PUNDIT Calibration Profile',
                'verbose_name_plural': 'PUNDIT Calibration Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pundittest',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The isolated scan folder/batch this test measurement belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='digital_eye.punditscanbatch'),
        ),
    ]
