# Generated by Django 5.2 on 2026-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0018_strengthcurve_se_adjustment_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddevice',
            name='calibration_expiry',
            field=models.DateField(blank=True, help_text='Date the calibration certificate lapses. Null means no expiry has been recorded — never defaulted to a computed date, because an instrument with no certificate on file must not appear calibrated until some assumed point.', null=True),
        ),
        migrations.AlterField(
            model_name='fielddevice',
            name='device_type',
            field=models.CharField(choices=[('tersus_gnss', 'Tersus GNSS (MVP SI)'), ('gpr', 'Ground Penetrating Radar'), ('pundit', 'PUNDIT Ultrasonic NDT'), ('scanner', '3D Laser Scanner'), ('slam', 'SLAM Handheld Scanner'), ('thermal', 'Thermal Imaging Camera'), ('other', 'Other Sensor')], db_index=True, max_length=30),
        ),
    ]
