# Generated by Django 4.2.30 on 2026-09-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0019_fielddevice_calibration_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddevice',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Maps this instrument's own export headers to the platform's contract keys. Empty means the export already speaks the template."),
        ),
    ]
