# Generated by Django 4.2.30 on 2026-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0020_fielddevice_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddevice',
            name='gateway_enabled',
            field=models.BooleanField(default=False, help_text="True when the platform has written this instrument's config for the field gateway. False means sync was never set up, not that it was set up and is idle."),
        ),
    ]
