# Generated by Django 5.2 on 2026-09-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0021_fielddevice_gateway_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddevice',
            name='default_floor',
            field=models.CharField(blank=True, default='', help_text='Default floor for gateway-pushed files', max_length=100),
        ),
        migrations.AddField(
            model_name='fielddevice',
            name='default_structural_element',
            field=models.CharField(blank=True, default='', help_text='Default structural element for gateway-pushed files', max_length=100),
        ),
        migrations.AddField(
            model_name='fielddevice',
            name='default_test_location',
            field=models.CharField(blank=True, default='', help_text='Default test location for gateway-pushed files', max_length=255),
        ),
        migrations.AddField(
            model_name='fielddevice',
            name='default_test_type',
            field=models.CharField(blank=True, default='', help_text='Default test type for gateway-pushed files', max_length=30),
        ),
    ]
