# Generated by Django 4.2.30 on 2026-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0022_fielddevice_default_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pundittest',
            name='quality_grade',
            field=models.CharField(choices=[('excellent', 'Excellent (>= 4.5 km/s)'), ('good', 'Good (3.75 – 4.5 km/s)'), ('questionable', 'Questionable (3.0 – 3.75 km/s)'), ('poor', 'Poor (2.0 – 3.0 km/s)'), ('very_poor', 'Very Poor (< 2.0 km/s)'), ('unverified', 'Unverified — velocity not plausible for concrete'), ('pending', 'Pending Analysis'), ('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('DOUBTFUL', 'Doubtful'), ('POOR', 'Poor'), ('VERY_POOR', 'Very Poor')], default='pending', max_length=50),
        ),
    ]
