# Generated by Django 5.2 on 2026-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0023_alter_pundittest_quality_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddevice',
            name='connection_protocol',
            field=models.CharField(blank=True, choices=[('usb', 'USB Wired'), ('bluetooth', 'Bluetooth Wireless'), ('wifi', 'Wi-Fi Hotspot / Network')], default='', help_text='Wireless or wired connection method (e.g. Wi-Fi, Bluetooth)', max_length=30),
        ),
    ]
