# Generated by Django 5.2 on 2026-09-25 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0024_fielddevice_connection_protocol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('protocol', models.CharField(choices=[('bluetooth', 'Bluetooth Wireless'), ('wifi', 'Wi-Fi Hotspot / Network'), ('cloud', 'Cloud Push (Screening Eagle)')], db_index=True, max_length=20)),
                ('rssi_dbm', models.IntegerField(blank=True, help_text='Received signal strength (dBm) at connection time', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Device IP (Wi-Fi) or client IP (Cloud)', null=True)),
                ('cloud_workspace_id', models.CharField(blank=True, default='', help_text='Screening Eagle workspace ID for cloud connections', max_length=255)),
                ('firmware_banner', models.CharField(blank=True, default='', help_text='Firmware version string received at handshake', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text="Diagnostic message when event is 'failed'")),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='digital_eye.fielddevice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
