# Generated by Django 5.2 on 2026-10-03 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0025_deviceconnectionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='punditanalysisreview',
            name='inspector_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='punditanalysisreview',
            name='inspector_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punditanalysisreview',
            name='inspector_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pundit_analysis_inspector_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='punditanalysisreview',
            name='decision',
            field=models.CharField(blank=True, choices=[('corroborated', 'Corroborated by reviewing engineer'), ('returned', 'Returned — revisions / further testing required')], default='', max_length=20),
        ),
    ]
