# Generated by Django 5.2 on 2026-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0026_punditanalysisreview_inspector_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punditanalysisreview',
            name='inspector_verdict',
            field=models.CharField(blank=True, choices=[('verified', 'Verified — field readings consistent'), ('requires_coring', 'Secondary coring recommended'), ('coupling_rechecked', 'Transducer coupling verified on site'), ('retest_recommended', 'Further testing / revision required')], default='', max_length=30),
        ),
    ]
