# Generated by Django 5.2 on 2026-10-04 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0027_punditanalysisreview_inspector_verdict'),
        ('evidence', '0004_alter_evidencerecord_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunditAnalysisComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_role', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='evidence.aianalysisrecord')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pundit_analysis_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
