# Generated by Django 5.2 on 2026-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0029_default_curve_exponential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pundittest',
            name='location_address',
            field=models.TextField(blank=True, default='', help_text="Inspector's description of the test location: street address, building, or how to reach the station"),
        ),
    ]
