# Generated by Django 5.2 on 2026-10-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_eye', '0019_punditscanbatch_visualobservation_and_more'),
        ('digital_eye', '0030_pundittest_location_address'),
    ]

    operations = [
    ]
