# Generated by Django 4.2.30 on 2026-09-02 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text='Base32 TOTP secret', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_counter', models.BigIntegerField(blank=True, help_text='TOTP step counter of the last accepted code (replay protection)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_two_factor_secret',
            },
        ),
    ]
