# Generated by Django 4.2.30 on 2026-09-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode'),
        ('accounts', '0005_emailverificationtoken'),
    ]

    operations = [
    ]
