# Generated by Django 4.2.30 on 2026-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed their onboarding flow.'),
        ),
    ]
