# Generated by Django 5.2 on 2026-09-17 13:03

import apps.data_import.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0006_inspection_check_out_time_and_more'),
        ('projects', '0008_project_geofence_radius_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(default=apps.data_import.models.generate_batch_reference, editable=False, max_length=32, unique=True)),
                ('inspector_name', models.CharField(blank=True, default='', help_text="Snapshot of the uploader's name at upload time. A snapshot rather than a join so provenance survives the account being closed.", max_length=255)),
                ('import_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('PDF', 'PDF')], help_text="What the file actually is, detected from its bytes rather than taken from the filename or the client's claim.", max_length=8)),
                ('record_type', models.CharField(blank=True, default='', help_text='The record kind this file carries (UPV, GPR, SLAM, FINDING). A single-kind file declares it once here; a mixed JSON file leaves it blank and each record carries its own.', max_length=20)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_url', models.CharField(blank=True, default='', max_length=1000)),
                ('storage_name', models.CharField(blank=True, default='', help_text='The storage backend key, kept so the stored file can be re-read', max_length=1000)),
                ('sha256_hash', models.CharField(blank=True, default='', help_text='SHA-256 over the stored bytes, computed in the same pass that writes them — so the hash attests the file that exists, not one the client says it sent.', max_length=64)),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='Row-level problems from the last validation pass')),
                ('errors_truncated', models.BooleanField(default=False, help_text='True when the error list was capped. A 50,000-row bad file must not produce a 50,000-entry response — but the caller has to know it was capped rather than assume it saw everything.')),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Records the file was read as, including ones that were rejected. A row rejected before a record could be formed still counts, so that valid + invalid always equals the number of rows the inspector can see in their own file.')),
                ('valid_record_count', models.PositiveIntegerField(default=0)),
                ('invalid_record_count', models.PositiveIntegerField(default=0, help_text='Records that failed validation. Any at all fails the batch.')),
                ('skipped_row_count', models.PositiveIntegerField(default=0, help_text='Rows whose every value is blank — skipped, and not records. A physically empty line is not counted here: it never reaches the reader as a row.')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(blank=True, help_text='The inspection this file belongs to, when it belongs to one. Findings use it; instrument readings do not.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='inspections.inspection')),
                ('inspector', models.ForeignKey(help_text='The user who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project every record in this file is written against', on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='projects.project')),
            ],
            options={
                'verbose_name': 'Import batch',
                'verbose_name_plural': 'Import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='The first row of the source file this record came from')),
                ('row_end', models.PositiveIntegerField(default=0, help_text='The last source row this record came from. Equal to row_number for a one-row record; wider for a grouped one (a UPV test is several consecutive reading rows and lands as a single registry row).')),
                ('record_type', models.CharField(max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=list, help_text='The source rows verbatim, before any interpretation')),
                ('record_data', models.JSONField(blank=True, default=dict, help_text='The record as the platform interpreted it, ready for its serializer')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=16)),
                ('error_message', models.TextField(blank=True, default='', help_text='Why this row was rejected, as a message a person can act on')),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_import.importbatch')),
            ],
            options={
                'verbose_name': 'Import record',
                'verbose_name_plural': 'Import records',
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['inspector', 'import_status'], name='data_import_inspect_e70ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['project', 'import_status'], name='data_import_project_300882_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['sha256_hash'], name='data_import_sha256__77729c_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['batch', 'validation_status'], name='data_import_batch_i_b1c10c_idx'),
        ),
    ]
