# Generated by Django 4.2.30 on 2026-09-02 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_agency_city_agency_collaboration_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('state_region', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('boundary_polygon', models.JSONField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, default='')),
                ('lead_officer_name', models.CharField(blank=True, default='', max_length=255)),
                ('lead_officer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='is_state_hq',
            field=models.BooleanField(default=False, help_text='State Headquarters Directorate — state-wide visibility'),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, help_text='Zonal/District jurisdiction the user is scoped to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='government.district'),
        ),
    ]
