# Generated by Django 5.2 on 2026-09-17 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_district_profile_is_state_hq_profile_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_number', models.CharField(help_text="The number printed on the inspector's physical badge", max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='The name the badge was issued to. A snapshot — it does not follow later edits to the user account.', max_length=255)),
                ('directorate', models.CharField(blank=True, default='', max_length=255)),
                ('accreditation_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('accreditation_expiry', models.DateField(blank=True, help_text='Null means no expiry is recorded — not that it never expires', null=True)),
                ('issued_by', models.CharField(blank=True, default='', max_length=255)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_accreditation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspector accreditation',
                'verbose_name_plural': 'Inspector accreditations',
                'ordering': ['badge_number'],
            },
        ),
    ]
