# Generated by Django 4.2.30 on 2026-08-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_stakeholdermessage_attachment_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdermeeting',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stakeholdermeeting',
            name='google_calendar_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='stakeholdermeeting',
            name='meet_link_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
