# Generated by Django 4.2.30 on 2026-09-20 13:59

import apps.stakeholders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0007_alter_consultant_hq_location_alter_consultant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimelineMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_id', models.CharField(db_index=True, max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('is_hold_point', models.BooleanField(default=False)),
                ('government_signoff', models.CharField(default='Pending', max_length=255)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryFinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('fee_category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_formatted', models.CharField(blank=True, default='', max_length=100)),
                ('issued_date', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('status', models.CharField(default='DUE', max_length=50)),
                ('paid_date', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary', models.CharField(blank=True, default='', max_length=255)),
                ('payment_gateway', models.CharField(default='Remita', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildingStageInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(db_index=True, default=apps.stakeholders.models.generate_ins_id, max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=100)),
                ('contractor_on_site', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_date', models.CharField(blank=True, default='', max_length=100)),
                ('time_slot', models.CharField(default='Morning (09:00 - 12:00)', max_length=100)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('has_ncr', models.BooleanField(default=False)),
                ('ncr_description', models.TextField(blank=True, default='')),
                ('ncr_remediation_proof', models.TextField(blank=True, default='')),
                ('ncr_deadline', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_inspections', to='stakeholders.inspector')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
