# Generated by Django 4.2.30 on 2026-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0009_licensedprofessional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholdermessage',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stakeholdermessage',
            name='recipient_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
