# Generated by Django 4.2.30 on 2026-09-02 20:18

import apps.evidence.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_project_district'),
        ('inspections', '0003_issue_nonconformancereport_issuecomment_and_more'),
        ('compliance', '0003_escalationrule_compliancereview_findings_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_reference', models.CharField(default=apps.evidence.models.generate_analysis_ref, max_length=40, unique=True)),
                ('analysis_type', models.CharField(choices=[('gpr', 'GPR Subsurface Analysis'), ('pundit', 'PUNDIT Ultrasonic NDT Analysis'), ('gnss', 'GNSS Positioning Analysis'), ('defect', 'Visual Defect Analysis'), ('thermal', 'Thermal Analysis'), ('bim', 'BIM Deviation Analysis'), ('correlation', 'Cross-Source Correlation'), ('project_intelligence', 'Project-Level Intelligence'), ('district_intelligence', 'District / HQ Intelligence')], db_index=True, max_length=40)),
                ('risk_level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('risk_score', models.FloatField(blank=True, help_text='Explainable computed risk 0.0–1.0 (deterministic math; null when not computable)', null=True)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('correlations', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('reasoning_log', models.TextField(blank=True, default='', help_text='Explainable reasoning: every input, weight and step of the computation')),
                ('requires_human_review', models.BooleanField(default=True)),
                ('confidence', models.FloatField(blank=True, help_text='Analysis confidence 0.0–1.0', null=True)),
                ('model_provider', models.CharField(blank=True, default='', max_length=50)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_reference', models.CharField(default=apps.evidence.models.generate_finding_ref, max_length=40, unique=True)),
                ('structural_element_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('bim_guid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('group_key', models.CharField(blank=True, db_index=True, default='', help_text='Stable correlation group key (element:<id> | guid:<guid> | spatial:<cluster> | source:<type>)', max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('risk_score', models.FloatField(blank=True, help_text='Computed multi-source risk 0.0–1.0', null=True)),
                ('reasoning', models.TextField(blank=True, default='', help_text='Explainable correlation reasoning: which sources agreed, weights applied, math')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Human Review'), ('accepted', 'Accepted by Reviewer'), ('rejected', 'Rejected / Dismissed'), ('modified', 'Modified by Reviewer'), ('escalated', 'Escalated (NCR / Statutory Inspection)')], db_index=True, default='pending_review', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='evidence.aianalysisrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('change_reason', models.CharField(choices=[('created', 'Finding Created by Correlation Engine'), ('modified', 'Modified by Human Reviewer'), ('decision', 'Human Review Decision'), ('escalated', 'Escalated to Statutory Process'), ('new_evidence', 'New Evidence Correlated')], max_length=30)),
                ('snapshot', models.JSONField(default=dict, help_text='Complete finding state at this revision')),
                ('notes', models.TextField(blank=True, default='')),
                ('revision_hash', models.CharField(blank=True, default='', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_revisions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='evidence.correlationfinding')),
            ],
            options={
                'ordering': ['finding', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_reference', models.CharField(default=apps.evidence.models.generate_evidence_ref, max_length=40, unique=True)),
                ('source_type', models.CharField(choices=[('scan_defect', 'Digital Eye — Visual Defect'), ('scan_thermal', 'Digital Eye — Thermal Anomaly'), ('scan_alignment', 'Digital Eye — BIM Alignment / Deviation'), ('scan_progress', 'Digital Eye — Progress Validation'), ('gpr', 'Digital Eye — GPR Subsurface Radar'), ('pundit', 'Digital Eye — PUNDIT Ultrasonic NDT'), ('gnss', 'Digital Eye — Tersus GNSS Positioning'), ('bim_element', 'Trimble Connect — BIM Element'), ('inspection_finding', 'Field Inspection Finding'), ('inspection', 'Field Inspection Record'), ('document', 'Approved Document'), ('live_stream', 'Live Stream Observation'), ('corrective_action', 'Corrective Action'), ('other', 'Other Source')], db_index=True, max_length=40)),
                ('structural_element_id', models.CharField(blank=True, db_index=True, default='', help_text='Structural element identifier, e.g. COL-C24', max_length=100)),
                ('bim_guid', models.CharField(blank=True, db_index=True, default='', help_text='IFC GlobalId / Trimble element GUID when known', max_length=64)),
                ('coordinates', models.JSONField(blank=True, help_text="{'latitude', 'longitude', 'x', 'y', 'z'} — whatever the source provides", null=True)),
                ('captured_at', models.DateTimeField(blank=True, db_index=True, help_text='When the evidence was captured in the field', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Source confidence 0.0–1.0 where the source provides one', null=True)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_evidence', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='correlationfinding',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='correlation_findings', to='evidence.evidencerecord'),
        ),
        migrations.AddField(
            model_name='correlationfinding',
            name='linked_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_findings', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='correlationfinding',
            name='linked_ncr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_findings', to='compliance.nonconformancereport'),
        ),
        migrations.AddField(
            model_name='correlationfinding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_findings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='correlationfinding',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_correlation_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aianalysisrecord',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='ai_analyses', to='evidence.evidencerecord'),
        ),
        migrations.AddField(
            model_name='aianalysisrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='findingrevision',
            constraint=models.UniqueConstraint(fields=('finding', 'revision_number'), name='unique_finding_revision'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['project', 'source_type'], name='evidence_ev_project_8ed5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['structural_element_id'], name='evidence_ev_structu_c9c290_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['bim_guid'], name='evidence_ev_bim_gui_4c7861_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_model', ''), _negated=True), fields=('source_model', 'source_id'), name='unique_evidence_source'),
        ),
        migrations.AddIndex(
            model_name='correlationfinding',
            index=models.Index(fields=['project', 'status'], name='evidence_co_project_b459b9_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationfinding',
            index=models.Index(fields=['risk_level'], name='evidence_co_risk_le_4a9133_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisrecord',
            index=models.Index(fields=['project', 'analysis_type'], name='evidence_ai_project_a902bd_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisrecord',
            index=models.Index(fields=['risk_level'], name='evidence_ai_risk_le_fc5dd8_idx'),
        ),
    ]
