# Generated by Django 5.2 on 2026-09-17 13:25

import apps.evidence.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('inspections', '0006_inspection_check_out_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='inspection',
            field=models.ForeignKey(blank=True, help_text='The inspection this evidence was gathered for, when there was one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='inspections.inspection'),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='source_type',
            field=models.CharField(choices=[('scan_defect', 'Digital Eye — Visual Defect'), ('scan_thermal', 'Digital Eye — Thermal Anomaly'), ('scan_alignment', 'Digital Eye — BIM Alignment / Deviation'), ('scan_progress', 'Digital Eye — Progress Validation'), ('gpr', 'Digital Eye — GPR Subsurface Radar'), ('pundit', 'Digital Eye — PUNDIT Ultrasonic NDT'), ('gnss', 'Digital Eye — Tersus GNSS Positioning'), ('bim_element', 'Trimble Connect — BIM Element'), ('inspection_finding', 'Field Inspection Finding'), ('inspection', 'Field Inspection Record'), ('document', 'Approved Document'), ('live_stream', 'Live Stream Observation'), ('corrective_action', 'Corrective Action'), ('uploaded_file', 'Uploaded File'), ('other', 'Other Source')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.evidence.models.evidence_file_upload_to)),
                ('file_name', models.CharField(blank=True, default='', help_text='The name as uploaded — kept even if storage renames it', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', help_text="The client's declared type. Not trusted, and not verified", max_length=120)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, default='', help_text='SHA-256 over the stored bytes, taken by reading them back from storage — so the hash attests the file that exists, not the one the client said it sent.', max_length=64)),
                ('storage_name', models.CharField(blank=True, default='', help_text='The storage backend key, kept so the bytes can be re-read', max_length=1000)),
                ('last_verify_ok', models.BooleanField(blank=True, help_text='None until a verification has run. True only when the stored bytes re-hash to the recorded digest; False when they do not; None with a note when the file was too large to re-hash.', null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verify_note', models.CharField(blank=True, default='', help_text='Why verification did not pass, or why it could not be run', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='evidence.evidencerecord')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence file',
                'verbose_name_plural': 'Evidence files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sha256_hash'], name='evidence_ev_sha256__06814b_idx')],
            },
        ),
    ]
