# Generated by Django 4.2.30 on 2026-09-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencerecord_inspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='model_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aianalysisrecord',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
