# Generated by Django 4.2.30 on 2026-10-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidencerecord_source_type'),
        ('evidence', '0004_alter_evidencerecord_source_type'),
    ]

    operations = [
    ]
