# Generated by Django 4.2.30 on 2026-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_merge_20261007_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencerecord',
            name='source_type',
            field=models.CharField(choices=[('photo', 'Field Inspection / Defect Photo'), ('voice_note', 'Field Voice Note / Audio Record'), ('scan_defect', 'Digital Eye — Visual Defect'), ('scan_thermal', 'Digital Eye — Thermal Anomaly'), ('scan_alignment', 'Digital Eye — BIM Alignment / Deviation'), ('scan_progress', 'Digital Eye — Progress Validation'), ('gpr', 'Digital Eye — GPR Subsurface Radar'), ('pundit', 'Digital Eye — PUNDIT Ultrasonic NDT'), ('gnss', 'Digital Eye — Tersus GNSS Positioning'), ('bim_element', 'Trimble Connect — BIM Element'), ('inspection_finding', 'Field Inspection Finding'), ('inspection', 'Field Inspection Record'), ('document', 'Approved Document'), ('live_stream', 'Live Stream Observation'), ('corrective_action', 'Corrective Action'), ('uploaded_file', 'Uploaded File'), ('photo', 'Field Photo Capture'), ('voice_note', 'Field Voice Note'), ('other', 'Other Source')], db_index=True, max_length=40),
        ),
    ]
