# Generated by Django 4.2.30 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_file_size_alter_document_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
