# Generated by Django 4.2.30 on 2026-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documenttemplate_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXPIRING_SOON', 'Expiring Soon'), ('ARCHIVED', 'Archived')], default='PENDING_REVIEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='author_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
