# Generated by Django 4.2.30 on 2026-10-06 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_coordinate_system_project_corner_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_alter_document_file_format_alter_document_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('report_digest', models.CharField(blank=True, max_length=255, null=True)),
                ('document_title', models.CharField(default='Statutory Engineering Report', max_length=255)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('requester_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('requester_role', models.CharField(default='Stakeholder', max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Access Granted'), ('REJECTED', 'Access Rejected')], default='PENDING', max_length=20)),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='documents.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_requests', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
