# Generated by Django 4.2.30 on 2026-09-02 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_agencyprofile_reporttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0003_issue_nonconformancereport_issuecomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_results', models.JSONField(blank=True, default=list, help_text='Item-by-item results [{item_id, title, result, notes, evidence_hashes}]')),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='[{file_name, sha256, url}] — every attached artifact with its checksum')),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_recorded_at', models.DateTimeField(blank=True, help_text='Device timestamp of the GPS fix', null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_hash', models.CharField(db_index=True, help_text='SHA-256 over checklist results + evidence checksums + GPS + timestamp', max_length=64)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='settings.inspectiontemplate')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='inspections.inspection')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('signature_text', models.TextField(blank=True, default='', help_text="Inspector's typed declaration, e.g. 'I confirm this inspection was executed at the recorded location and time.'")),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signoff_hash', models.CharField(db_index=True, max_length=64)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_signoffs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signoff', to='inspections.inspectionsubmission')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
