# Generated by Django 4.2.30 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspectionsubmission_inspectionsignoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
