# Generated by Django 5.2 on 2026-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_finding_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checkout_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='checkout_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='geofence_distance_m',
            field=models.FloatField(blank=True, help_text='Measured distance from the recorded site point; null if not measurable.', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='geofence_reason',
            field=models.CharField(blank=True, default='', help_text='Why the state was reached, e.g. OUTSIDE_RADIUS.', max_length=40),
        ),
        migrations.AddField(
            model_name='inspection',
            name='geofence_state',
            field=models.CharField(blank=True, default='', help_text='VERIFIED | OUTSIDE | UNVERIFIABLE. Empty string = never evaluated.', max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, help_text='Device-reported horizontal accuracy in metres; null if not sent.', null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='gps_verified',
            field=models.BooleanField(default=False, help_text="True only when the project has recorded site coordinates AND the check-in point is within the effective geofence radius AND the device's reported accuracy does not exceed that radius. False in every other case, including 'could not be verified'. Written only by InspectionExecutionService.checkin()."),
        ),
    ]
