# Generated by Django 5.2 on 2026-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspection_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='attendance_log',
            field=models.JSONField(blank=True, default=list, help_text='[{name, role, organization, signature}] - Client/site representatives present'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='visual_site_observations',
            field=models.TextField(blank=True, help_text="Inspector's visual observations on site", null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='visual_site_photos',
            field=models.JSONField(blank=True, default=list, help_text='Uploaded photos for visual observations'),
        ),
    ]
