# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
