# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_escalationrule_compliancereview_findings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereview',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compliancereview',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nonconformancereport',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformancereport',
            name='reported_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
