# Generated by Django 4.2.30 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alter_compliancereview_auditor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionplan',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
