# Generated by Django 4.2.30 on 2026-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_correctiveactionplan_assignee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryrequirement',
            name='status',
            field=models.CharField(choices=[('Pending Assessment', 'Pending Assessment'), ('Compliant', 'Compliant'), ('At Risk', 'At Risk'), ('Non-Compliant', 'Non-Compliant')], default='Pending Assessment', max_length=50),
        ),
    ]
