# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0003_alter_bimprogressvalidation_simulation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimannotation',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='element_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='uploaded_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bimprogressvalidation',
            name='completed_elements_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bimprogressvalidation',
            name='total_elements_count',
            field=models.IntegerField(default=0),
        ),
    ]
