# Generated by Django 4.2.30 on 2026-09-28 17:29

import apps.public_portal.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, default=apps.public_portal.models.generate_notice_ref, max_length=100, unique=True)),
                ('notice_type', models.CharField(choices=[('STOP_WORK', 'Stop-Work Order'), ('SAFETY_ADVISORY', 'Safety Advisory'), ('STAGE_CLEARANCE', 'Stage Clearance'), ('REGULATORY_UPDATE', 'Regulatory Update')], default='SAFETY_ADVISORY', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issuing_agency', models.CharField(default='Lagos State Building Control Agency (LASBCA)', max_length=255)),
                ('target_lga', models.CharField(default='Statewide', max_length=100)),
                ('target_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=50)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicPublicationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('action', models.CharField(default='PUBLISH', max_length=50)),
                ('published_by_name', models.CharField(blank=True, default='Directorate of Public Records', max_length=255)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('governance_reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='violationreport',
            options={'ordering': ['-reported_at']},
        ),
        migrations.AddField(
            model_name='violationreport',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
