# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_agencyprofile_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationlog',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='payload_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='battery_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='horizontal_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='rtk_fix_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='satellites_tracked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tersusdevice',
            name='vertical_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
