# Generated by Django 4.2.30 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_integrationlog_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsystemintegration',
            name='endpoint_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
