# Generated by Django 4.2.30 on 2026-09-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_district_profile_is_state_hq_profile_district'),
        ('settings', '0006_alter_documentsystemintegration_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invitations', to='government.agency'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='assigned_projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_invitations', to='government.district'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='temporary_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
