# Generated by Django 4.2.30 on 2026-08-28 12:17

import apps.monitoring.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        ('monitoring', '0003_siteverification_cadastral_beacon_numbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysiteupdate',
            options={'ordering': ['-inspection_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='field_verification_stamp',
            field=models.JSONField(blank=True, default=dict, help_text='GPS Lock, timestamp, and field seal'),
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='inspection_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_daily_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='inspector_badge',
            field=models.CharField(default='LASG-INSP-STR-042', max_length=100),
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='inspector_name',
            field=models.CharField(default='Engr. Abdulwahab Onike', max_length=255),
        ),
        migrations.AddField(
            model_name='dailysiteupdate',
            name='origin_type',
            field=models.CharField(choices=[('FIELD_INSPECTOR', 'Field Inspector (Direct On-Site)'), ('PROXY_OFFICE_SUPERVISOR', 'Office Staff Proxy (Documented)'), ('OFFLINE_FIELD_SYNC', 'Offline Field Device Sync')], default='FIELD_INSPECTOR', max_length=50),
        ),
        migrations.CreateModel(
            name='MissedSiteVisitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_reference', models.CharField(blank=True, db_index=True, default=apps.monitoring.models.generate_msv_ref, max_length=100, null=True)),
                ('inspector_name', models.CharField(default='Engr. Abdulwahab Onike', max_length=255)),
                ('inspector_badge', models.CharField(default='LASG-INSP-STR-042', max_length=100)),
                ('scheduled_date', models.DateField(default=datetime.date.today)),
                ('reason_category', models.CharField(choices=[('ADVERSE_WEATHER', 'Adverse Weather / Heavy Downpour'), ('ACCESS_DENIED', 'Site Access Denied by Developer / Contractor'), ('SITE_INACCESSIBLE', 'Flooded Road / Inaccessible Approach Road'), ('SECURITY_CONCERN', 'Safety Hazard / Site Unrest / Security Incident'), ('EQUIPMENT_BREAKDOWN', 'Transport / Rover / Device Hardware Failure'), ('EMERGENCY_REASSIGNMENT', 'Reassigned to Emergency Structural Audit'), ('DEVELOPER_UNAVAILABLE', 'Site Key Personnel / Site Engineer Unavailable'), ('ILLNESS_LEAVE', 'Inspector Official / Medical Leave'), ('OTHER', 'Other Documented Justification')], default='ADVERSE_WEATHER', max_length=60)),
                ('justification_notes', models.TextField(help_text='Detailed explanation of why the site visit could not proceed')),
                ('evidence_photos', models.JSONField(blank=True, default=list, help_text='Supporting photos e.g. locked gate, flooded road')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted / Pending Review'), ('ACKNOWLEDGED', 'Supervisor Acknowledged'), ('JUSTIFIED', 'Justified Non-Attendance'), ('FLAGGED_UNJUSTIFIED', 'Flagged as Unjustified'), ('ESCALATED', 'Escalated to Directorate')], default='SUBMITTED', max_length=50)),
                ('supervisor_acknowledgment', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missed_site_visits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_visits', to='projects.project')),
                ('supervisor_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_missed_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
