# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_dailysiteupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysiteupdate',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='missedsitevisitrecord',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
