# Generated by Django 4.2.30 on 2026-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_dailysiteupdate_inspector_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysiteupdate',
            name='inspector_badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missedsitevisitrecord',
            name='inspector_badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteverification',
            name='verified_by_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
