# Generated by Django 5.2 on 2026-09-17 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_item_id', models.CharField(help_text='Client-generated idempotency key, unique per inspector', max_length=128)),
                ('entity_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('FINDING', 'Finding'), ('STOP_WORK_ORDER', 'Stop work order'), ('EVIDENCE', 'Evidence record'), ('TELEMETRY', 'Telemetry session')], db_index=True, max_length=32)),
                ('entity_id', models.CharField(blank=True, default='', help_text="The client's identifier for the target row", max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(default='', editable=False, max_length=64)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='', help_text='Why the last attempt failed, as a message. Never a stack trace: this string is returned to a mobile client.')),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When a processor took this item; cleared on completion', null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(help_text='The user whose device queued this write', on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync queue item',
                'verbose_name_plural': 'Sync queue items',
                'ordering': ['queued_at', 'id'],
                'indexes': [models.Index(fields=['inspector', 'sync_status'], name='sync_syncqu_inspect_f196bc_idx'), models.Index(fields=['inspector', 'entity_type', 'entity_id'], name='sync_syncqu_inspect_304f51_idx'), models.Index(fields=['sync_status', 'queued_at'], name='sync_syncqu_sync_st_d544b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('inspector', 'client_item_id'), name='uniq_sync_item_inspector_client_item')],
            },
        ),
    ]
