# Generated by Django 5.2.8 on 2026-08-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('scans', '0002_bimalignmentresult_defect_processingtask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scansession',
            name='project_id',
        ),
        migrations.AddField(
            model_name='scansession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='projects.project'),
        ),
    ]
