# Generated by Django 5.2.8 on 2026-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_remove_scansession_project_id_scansession_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='rgb_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='thermal_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
