# Generated by Django 5.2.8 on 2026-08-13 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_scansession_rgb_url_scansession_thermal_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('lidar', 'LiDAR Point Cloud'), ('rgb', 'RGB Image'), ('thermal', 'Thermal Image'), ('gps', 'GPS Telemetry'), ('gaussian_splat', '3D Gaussian Splat'), ('bim', 'BIM Model'), ('other', 'Other')], max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scans.scansession')),
            ],
        ),
    ]
