# Generated by Django 5.2.8 on 2026-08-13 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scanfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_score', models.FloatField(help_text='Calculated progress score (0.0 to 1.0)')),
                ('covered_area_sqm', models.FloatField(blank=True, help_text='Total scanned area mapped to BIM.', null=True)),
                ('volume_metrics', models.JSONField(blank=True, help_text='Volumetric data if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_validation', to='scans.scansession')),
            ],
        ),
    ]
