# Generated by Django 5.2.8 on 2026-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_progressvalidationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='is_false_positive',
            field=models.BooleanField(default=False, help_text='Flagged as false positive by multimodal AI'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='type',
            field=models.CharField(choices=[('crack', 'Crack'), ('spalling', 'Spalling'), ('corrosion', 'Corrosion'), ('thermal_anomaly', 'Thermal Anomaly'), ('deformation', 'Deformation'), ('delamination', 'Delamination')], max_length=50),
        ),
    ]
