# Generated by Django 5.2.8 on 2026-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_defect_confidence_score_defect_is_false_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalanomaly',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
