# Generated by Django 5.2.8 on 2026-08-17 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_applicable_regulations_project_approval_date_and_more'),
        ('scans', '0008_thermalanomaly_description_thermalanomaly_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_area', models.CharField(help_text="e.g., 'Floor 3, Zone A'", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_plans', to='projects.project')),
            ],
        ),
    ]
