# Generated by Django 5.2.8 on 2026-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_scanplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimalignmentresult',
            name='top_deviations',
            field=models.JSONField(blank=True, help_text='List of top deviations', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='evidence_link',
            field=models.URLField(blank=True, help_text='Link to the specific point cloud data or raw evidence', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='grid_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='room_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score', null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='evidence_link',
            field=models.URLField(blank=True, help_text='Link to the specific point cloud data or raw evidence', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='grid_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='room_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
