# Generated by Django 5.2.8 on 2026-08-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_bimalignmentresult_top_deviations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('element', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=255)),
                ('measured', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='scans.scansession')),
            ],
        ),
    ]
