# Generated by Django 5.1.15 on 2026-08-20 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0011_compliancecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Serial/asset tag, e.g. NAVIS-V3-001', max_length=100, unique=True)),
                ('model', models.CharField(blank=True, default='', help_text='e.g. Tersus MVP S1', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, help_text='Percent 0-100, reported by the device', null=True)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, help_text='Last reported position', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Last reported position', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.AddField(
            model_name='scanplan',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Target area latitude, for the plan map view', null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Target area longitude, for the plan map view', null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='operator',
            field=models.CharField(blank=True, default='', help_text='Assigned operator name or ID', max_length=100),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Planned start of the survey', null=True),
        ),
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20)),
                ('total_checks', models.IntegerField(default=0)),
                ('passed_checks', models.IntegerField(default=0)),
                ('failed_checks', models.IntegerField(default=0)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to='scans.scansession')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GnssTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fix_rate', models.FloatField(help_text='Percentage of epochs with an RTK fix (0-100)')),
                ('fix_type', models.CharField(choices=[('rtk_fixed', 'RTK Fixed'), ('rtk_float', 'RTK Float'), ('dgps', 'DGPS'), ('single', 'Single'), ('none', 'No Fix')], default='rtk_fixed', max_length=20)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('horizontal_accuracy_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gnss_telemetry', to='scans.scansession')),
                ('scanner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gnss_telemetry', to='scans.scanner')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='scanplan',
            name='scanner',
            field=models.ForeignKey(blank=True, help_text='Device assigned to carry out this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_plans', to='scans.scanner'),
        ),
    ]
