# Generated by Django 5.2 on 2026-08-21 03:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0012_scanner_scanplan_latitude_scanplan_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scans.scanner')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_alerts', to='scans.scansession')),
            ],
        ),
    ]
