# Generated by Django 4.2.30 on 2026-08-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0013_hardwarealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='sensors_used',
            field=models.JSONField(blank=True, default=list, help_text='List of sensors required for the scan'),
        ),
    ]
