# Generated by Django 5.2 on 2026-08-31 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_scanplan_sensors_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWorkFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('flagged_by', models.EmailField(blank=True, default='', help_text='Email of the user who raised the flag', max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_work_flags', to='scans.compliancecheck')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_work_flags', to='scans.scansession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
