# Generated by Django 5.2 on 2026-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_stopworkflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='bbox_xmax',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) right edge of the defect in the source image', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='bbox_xmin',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) left edge of the defect in the source image', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='bbox_ymax',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) bottom edge of the defect in the source image', null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='bbox_ymin',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) top edge of the defect in the source image', null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='bbox_xmax',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) right edge of the anomaly in the thermal image', null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='bbox_xmin',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) left edge of the anomaly in the thermal image', null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='bbox_ymax',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) bottom edge of the anomaly in the thermal image', null=True),
        ),
        migrations.AddField(
            model_name='thermalanomaly',
            name='bbox_ymin',
            field=models.FloatField(blank=True, help_text='Normalised (0-1) top edge of the anomaly in the thermal image', null=True),
        ),
    ]
