# Generated by Django 5.2 on 2026-08-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0016_defect_bbox_xmax_defect_bbox_xmin_defect_bbox_ymax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimalignmentresult',
            name='clashes',
            field=models.JSONField(blank=True, help_text='Full clash-detection results persisted when the alignment ran', null=True),
        ),
    ]
