# Generated by Django 5.2 on 2026-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0017_bimalignmentresult_clashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='type',
            field=models.CharField(choices=[('crack', 'Crack'), ('spalling', 'Spalling'), ('corrosion', 'Corrosion'), ('thermal_anomaly', 'Thermal Anomaly'), ('deformation', 'Deformation'), ('delamination', 'Delamination'), ('honeycombing', 'Concrete Honeycombing'), ('voids', 'Internal Voids'), ('moisture_ingress', 'Moisture Ingress'), ('reinforcement_exposure', 'Reinforcement Exposure')], max_length=50),
        ),
    ]
