# Generated by Django 4.2.30 on 2026-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_audit_reference_auditevent_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='session_id',
            field=models.UUIDField(blank=True, help_text='UUID of the parent ScanSession, for easy timeline queries.', null=True),
        ),
    ]
