# Generated by Django 5.2 on 2026-08-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditevent_event_type_auditevent_metadata_and_more'),
        ('audit', '0003_auditevent_session_id'),
    ]

    operations = [
    ]
