# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_merge_20260829_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='signature_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
