# Generated by Django 4.2.30 on 2026-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditevent_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='user_name',
            field=models.CharField(default='System', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='user_role',
            field=models.CharField(default='System', max_length=100),
        ),
    ]
