# Generated by Django 4.2.30 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentperformancemetric',
            name='efficiency_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentperformancemetric',
            name='pending_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departmentperformancemetric',
            name='turnaround_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='departmentperformancemetric',
            name='workload_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='officerperformancerecord',
            name='average_review_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='officerperformancerecord',
            name='inspections_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officerperformancerecord',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officerperformancerecord',
            name='sla_adherence_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentalert',
            name='primary_vulnerability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessmentalert',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
