# Generated by Django 4.2.30 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_departmentperformancemetric_efficiency_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Queue'), ('Generating', 'Generating Data'), ('Ready', 'Ready For Download'), ('Failed', 'Generation Failed')], default='Pending', max_length=50),
        ),
    ]
