# Generated by Django 5.2.8 on 2026-08-06 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0002_bimalignmentresult_defect_processingtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scans.scansession')),
            ],
        ),
    ]
