# Generated by Django 5.2.8 on 2026-08-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='defect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='mean_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
