# Generated by Django 5.2.8 on 2026-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_qualityreport_anomaly_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='ai_model_version',
            field=models.CharField(default='NEXUCON-AI v1.2', max_length=50),
        ),
        migrations.AddField(
            model_name='qualityreport',
            name='report_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
