# Generated by Django 5.2.8 on 2026-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_qualityreport_ai_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='overall_ai_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence for the generated text/recommendations', null=True),
        ),
    ]
