# Generated by Django 5.1.15 on 2026-08-20 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_qualityreport_overall_ai_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('progress', 'Progress Report'), ('deviation', 'Deviation Analysis'), ('qaqc', 'QA/QC Summary'), ('earthworks', 'Earthworks Volume'), ('compliance', 'Compliance Summary')], max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
