# Generated by Django 5.2 on 2026-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='report_type',
            field=models.CharField(choices=[('progress', 'Progress Report'), ('deviation', 'Deviation Analysis'), ('qaqc', 'QA/QC Summary'), ('earthworks', 'Earthworks Volume'), ('compliance', 'Compliance Summary')], default='qaqc', help_text='Which template the report was generated from; drives the sections included in the PDF.', max_length=30),
        ),
    ]
