# Generated by Django 4.2.30 on 2026-09-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0007_seed_report_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_kind', models.CharField(choices=[('ndt', 'NDT / PUNDIT (BS 1881-203)')], default='ndt', max_length=30)),
                ('report_reference', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='reports/ndt/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_checksum', models.CharField(db_index=True, max_length=64)),
                ('content_key', models.CharField(db_index=True, help_text='Deterministic digest of the underlying records (what the report\'s integrity section hashes) — used to dedupe re-generations of identical content.', max_length=64)),
                ('test_count', models.IntegerField(default=0)),
                ('assessed_count', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'All strength-assessed tests pass the 25 MPa threshold'), ('FLAGGED_DEFECTS', 'Deficient tests recorded'), ('NOT_ASSESSED', 'No strength-assessed tests in this dossier')], default='NOT_ASSESSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='archivedreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_kind', 'content_key'), name='uniq_archived_report_content'),
        ),
    ]
