# Generated by Django 4.2.30 on 2026-09-10 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_project_cold_storage_project_cold_stored_at'),
        ('reports', '0008_archivedreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSectionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_section_overrides', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_section_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section_key'],
            },
        ),
        migrations.CreateModel(
            name='ReportCMSPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cms_passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportsectionoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('section_key',), name='uniq_platform_report_section_override'),
        ),
        migrations.AddConstraint(
            model_name='reportsectionoverride',
            constraint=models.UniqueConstraint(fields=('project', 'section_key'), name='uniq_project_report_section_override'),
        ),
    ]
