# Generated by Django 4.2.30 on 2026-09-11 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_project_cold_storage_project_cold_stored_at'),
        ('reports', '0009_reportsectionoverride_reportcmspassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.FileField(blank=True, default='', help_text='Client/consultant logo stamped on the report (PNG with transparency recommended)', upload_to='reports/branding/%Y/%m/')),
                ('logo_position', models.CharField(choices=[('top-left', 'Top left'), ('top-right', 'Top right'), ('bottom-left', 'Bottom left'), ('bottom-right', 'Bottom right')], default='top-right', max_length=20)),
                ('logo_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('watermark', models.FileField(blank=True, default='', help_text='Optional additional watermark image centred behind the page body at the chosen opacity', upload_to='reports/branding/%Y/%m/')),
                ('watermark_opacity_pct', models.PositiveIntegerField(default=50, help_text='Watermark opacity 0-100 (applied at render time)')),
                ('watermark_position', models.CharField(choices=[('center', 'Centre'), ('top-left', 'Top left'), ('top-right', 'Top right')], default='center', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_branding', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_branding_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
