# Generated by Django 4.2.30 on 2026-09-13 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_boundary_remove_project_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0011_reportbranding_cover_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSignOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved_by_name', models.CharField(blank=True, default='', help_text='The COREN-registered engineer approving the report', max_length=150)),
                ('qualification', models.CharField(blank=True, default='', help_text="e.g. 'B.Sc (Eng), M.Sc, MNSE' — as recorded", max_length=150)),
                ('coren_registration_no', models.CharField(blank=True, default='', help_text='COREN registration number of the approving engineer', max_length=60)),
                ('firm_name', models.CharField(blank=True, default='', help_text='Company / firm of the approving engineer', max_length=150)),
                ('signature_image', models.FileField(blank=True, default='', help_text='Optional scanned signature image of the approving engineer', upload_to='reports/signoff/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_signoff', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_signoff_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
