# Generated by Django 4.2.30 on 2026-09-15 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_remove_project_boundary_remove_project_location'),
        ('reports', '0013_reportversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbranding',
            name='logo_position',
            field=models.CharField(choices=[('top-left', 'Top left'), ('top-right', 'Top right'), ('bottom-left', 'Bottom left'), ('bottom-right', 'Bottom right'), ('center', 'Centre')], default='top-right', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportSectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=80)),
                ('is_custom', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_section_configs', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_section_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportsectionconfig',
            constraint=models.UniqueConstraint(fields=('project', 'section_key'), name='uniq_project_report_section_config'),
        ),
    ]
