# Generated by Django 5.2 on 2026-09-17 10:10

import apps.telemetry.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_eye', '0018_strengthcurve_se_adjustment_factor_and_more'),
        ('projects', '0008_project_geofence_radius_m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_reference', models.CharField(default=apps.telemetry.models.generate_session_ref, max_length=40, unique=True)),
                ('operator_name', models.CharField(blank=True, default='', help_text='Snapshot of the operator at capture time — survives user deletion', max_length=255)),
                ('data_type', models.CharField(choices=[('gpr', 'Ground Penetrating Radar'), ('pundit', 'PUNDIT Ultrasonic NDT'), ('gnss', 'GNSS / RTK Survey'), ('scan', '3D Scan / SLAM')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open — device streaming'), ('ENDED', 'Ended — capture complete, not yet promoted'), ('ABORTED', 'Aborted — capture abandoned')], db_index=True, default='OPEN', max_length=20)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending — not yet promoted'), ('SYNCED', 'Synced — rows written to the registry'), ('FAILED', 'Failed — promotion rejected, see sync_error')], db_index=True, default='PENDING', max_length=20)),
                ('session_start', models.DateTimeField(blank=True, help_text='Device-reported start time; null when the device reported none', null=True)),
                ('session_end', models.DateTimeField(blank=True, help_text='Device-reported end time; null while the session is open', null=True)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('session_config', models.JSONField(blank=True, default=dict, help_text='Session-wide inputs applied to the promoted record')),
                ('data_payload', models.JSONField(blank=True, null=True)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sync_error', models.TextField(blank=True, default='', help_text="Why promotion was rejected, in the operator's terms")),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='The physical instrument this session was captured on', on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_sessions', to='digital_eye.fielddevice')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_sessions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(help_text='Device-assigned position within the session, starting at 1')),
                ('payload', models.JSONField(help_text='The measurement as the device sent it, unmodified')),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('chain_hash', models.CharField(blank=True, default='', max_length=64)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Device-reported capture time for this row; null when not reported', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='telemetry.telemetrysession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='telemetrysession',
            index=models.Index(fields=['device', 'status'], name='telemetry_t_device__18e863_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrysession',
            index=models.Index(fields=['project', 'data_type'], name='telemetry_t_project_41cb4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetrypacket',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_telemetry_packet_session_sequence'),
        ),
    ]
