# Generated by Django 4.2.30 on 2026-09-17 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital_eye', '0019_fielddevice_calibration_expiry_and_more'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysession',
            name='source_file_name',
            field=models.CharField(blank=True, default='', help_text='Original filename of the imported export, as the operator chose it', max_length=255),
        ),
        migrations.AddField(
            model_name='telemetrysession',
            name='source_file_sha256',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the stored bytes, so the parse can be re-checked', max_length=64),
        ),
        migrations.AddField(
            model_name='telemetrysession',
            name='source_file_storage_name',
            field=models.CharField(blank=True, default='', help_text='Storage key of the retained export', max_length=500),
        ),
        migrations.AddField(
            model_name='telemetrysession',
            name='transport',
            field=models.CharField(blank=True, choices=[('BLE', 'Bluetooth — instrument to app'), ('WIFI', 'Direct Wi-Fi — instrument to network'), ('CLOUD', 'Cloud push — gateway to platform'), ('FILE', 'Export file — instrument to file to app'), ('MANUAL', 'Manual entry')], db_index=True, default='', help_text='How the capture arrived; blank means it was not recorded', max_length=10),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="What this credential is for, in the issuer's words", max_length=255)),
                ('key_prefix', models.CharField(max_length=20)),
                ('hashed_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means no expiry was set — not that it never expires', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(help_text='The one instrument this credential may push as', on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='digital_eye.fielddevice')),
                ('issued_by', models.ForeignKey(blank=True, help_text='The officer who provisioned this device; the token acts as them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['device', 'revoked_at'], name='telemetry_d_device__9c6980_idx')],
            },
        ),
    ]
