import uuid
from django.db import models
from django.utils import timezone


class BIMStructuralElement(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    element_guid = models.CharField(max_length=100, default=uuid.uuid4)
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=50, default='COLUMN')
    discipline = models.CharField(max_length=50, default='Structural')
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='structural_elements', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    model_id = models.CharField(max_length=100, blank=True, null=True)
    model_name = models.CharField(max_length=255, blank=True, null=True)
    grid_location = models.CharField(max_length=100, blank=True, default='')
    level = models.CharField(max_length=100, blank=True, default='')
    elevation_level_m = models.FloatField(null=True, blank=True)
    coordinates_3d = models.JSONField(default=dict, blank=True)
    bounding_box = models.JSONField(default=dict, blank=True)
    designed_concrete_grade = models.CharField(max_length=50, default='C35/45')
    concrete_grade_specified = models.CharField(max_length=50, blank=True, null=True)
    designed_rebar_spacing_mm = models.IntegerField(default=150)
    designed_cover_depth_mm = models.IntegerField(default=40)
    gpr_clearance_status = models.CharField(max_length=50, default='VERIFIED')
    pundit_clearance_status = models.CharField(max_length=50, default='VERIFIED')
    ai_anomaly_count = models.IntegerField(default=0)
    open_findings_count = models.IntegerField(default=0)
    last_inspected_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.grid_location})"


class TrimbleConnection(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='trimble_connections', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, default='Project')
    trimble_project_id = models.CharField(max_length=100, default='TC-PRJ-99201')
    trimble_project_name = models.CharField(max_length=255, default='CDE Model Sync')
    region = models.CharField(max_length=50, default='EU-West')
    status = models.CharField(max_length=50, default='CONNECTED')
    last_sync_at = models.DateTimeField(default=timezone.now)
    synced_models_count = models.IntegerField(default=12)
    synced_elements_count = models.IntegerField(default=1420)
    bcf_topics_count = models.IntegerField(default=4)
    webhook_active = models.BooleanField(default=True)

    def __str__(self):
        return f"Trimble Connect - {self.project_name} ({self.status})"


class GPRScan(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    scan_reference = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='gpr_scans', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element = models.ForeignKey(BIMStructuralElement, on_delete=models.SET_NULL, null=True, blank=True, related_name='gpr_scans')
    structural_element_id_str = models.CharField(max_length=100, blank=True, null=True)
    structural_element_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element_guid = models.CharField(max_length=100, blank=True, null=True)
    grid_axis = models.CharField(max_length=100, default='Grid 4-C to 4-D')
    antenna_frequency = models.CharField(max_length=50, default='2.0_GHZ')
    device_name = models.CharField(max_length=255, default='Proceq GS8000 Subsurface GPR')
    operator_name = models.CharField(max_length=255, default='Engr. K. Adeyemi (Lead Geophysicist)')
    survey_date = models.DateField(default=timezone.now)
    transect_length_m = models.FloatField(default=12.5)
    max_penetration_depth_m = models.FloatField(default=0.8)
    measured_rebar_spacing_mm = models.IntegerField(default=150)
    specified_rebar_spacing_mm = models.IntegerField(default=150)
    measured_cover_depth_mm = models.IntegerField(default=45)
    rebar_deficiency_detected = models.BooleanField(default=False)
    void_detected = models.BooleanField(default=False)
    delamination_detected = models.BooleanField(default=False)
    utility_strike_hazard = models.BooleanField(default=False)
    dielectric_constant = models.FloatField(default=6.2)
    dielectric_permittivity = models.FloatField(default=6.2)
    radargram_image_url = models.TextField(default='https://res.cloudinary.com/depeqzb6z/image/upload/v1779868806/Make_it_look_like_an_202605192308_1_rdayse.png')
    c_scan_heatmap_url = models.TextField(blank=True, null=True)
    raw_data_file_url = models.TextField(blank=True, null=True)
    file_size = models.CharField(max_length=50, default='14.2 MB')
    status = models.CharField(max_length=50, default='VERIFIED')
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.scan_reference} - {self.grid_axis}"


class PunditTest(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    test_reference = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='pundit_tests', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element = models.ForeignKey(BIMStructuralElement, on_delete=models.SET_NULL, null=True, blank=True, related_name='pundit_tests')
    structural_element_id_str = models.CharField(max_length=100, blank=True, null=True)
    structural_element_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element_guid = models.CharField(max_length=100, blank=True, null=True)
    test_location = models.CharField(max_length=255, default='Column C-102 (Level 2 Mid-Height)')
    device_model = models.CharField(max_length=255, default='Proceq Pundit PL-200 UPV')
    transducer_type = models.CharField(max_length=50, default='DIRECT')
    transducer_frequency_khz = models.IntegerField(default=54)
    path_length_mm = models.FloatField(default=400.0)
    transit_time_us = models.FloatField(default=94.2)
    pulse_velocity_ms = models.FloatField(default=4246.0)
    estimated_compressive_strength_mpa = models.FloatField(default=42.5)
    concrete_quality_rating = models.CharField(max_length=50, default='EXCELLENT')
    estimated_crack_depth_mm = models.FloatField(null=True, blank=True)
    waveform_samples = models.JSONField(default=list, blank=True)
    operator_name = models.CharField(max_length=255, default='Engr. F. Balogun (NDE Specialist)')
    test_date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=50, default='VERIFIED')
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.test_reference} - {self.test_location}"


class DigitalEyeFinding(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    finding_reference = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='digital_eye_findings', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element_id_str = models.CharField(max_length=100, blank=True, null=True)
    structural_element_name = models.CharField(max_length=255, blank=True, null=True)
    structural_element_guid = models.CharField(max_length=100, blank=True, null=True)
    gpr_scan_id = models.CharField(max_length=100, blank=True, null=True)
    pundit_test_id = models.CharField(max_length=100, blank=True, null=True)
    taxonomy = models.CharField(max_length=100, default='REBAR_SPACING_DEFICIENCY')
    title = models.CharField(max_length=255)
    description = models.TextField()
    severity = models.CharField(max_length=50, default='HIGH')
    confidence_score = models.FloatField(default=92.0)
    depth_mm = models.FloatField(null=True, blank=True)
    deviation_mm = models.FloatField(null=True, blank=True)
    gps_coordinates = models.JSONField(default=dict, blank=True)
    evidence_photos = models.JSONField(default=list, blank=True)
    radargram_snippet_url = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=50, default='OPEN')
    ncr_reference = models.CharField(max_length=100, blank=True, null=True)
    bcf_topic_guid = models.CharField(max_length=100, blank=True, null=True)
    assigned_inspector = models.CharField(max_length=255, blank=True, null=True)
    resolution_deadline = models.DateField(null=True, blank=True)
    corrective_action = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.finding_reference}: {self.title}"


class AIAnalysisRecord(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='ai_analyses', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    scan_reference = models.CharField(max_length=100, default='SCAN-AI-01')
    model_version = models.CharField(max_length=100, default='Nexucon Structural-Vision v3.2 + GPR-Inversion')
    analysis_type = models.CharField(max_length=50, default='MULTI_MODAL_FUSION')
    analyzed_at = models.DateTimeField(default=timezone.now)
    confidence_score = models.FloatField(default=96.4)
    overall_health_score = models.FloatField(default=94.0)
    total_elements_scanned = models.IntegerField(default=48)
    anomalies_detected = models.IntegerField(default=2)
    critical_defects_count = models.IntegerField(default=0)
    compliance_check_passed = models.BooleanField(default=True)
    findings = models.JSONField(default=list, blank=True)
    thermal_metrics = models.JSONField(default=dict, blank=True)
    deviation_summary = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class ProcessingQueueJob(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    job_reference = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='processing_jobs', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    device_id = models.CharField(max_length=100, default='TER-S1-008')
    source_type = models.CharField(max_length=50, default='GPR_RADAR_GS8000')
    stage = models.CharField(max_length=50, default='COMPLETED')
    progress_percentage = models.IntegerField(default=100)
    node_type = models.CharField(max_length=50, default='CLOUD_GPU_CLUSTER')
    started_at = models.DateTimeField(default=timezone.now)
    completed_at = models.DateTimeField(null=True, blank=True)
    file_count = models.IntegerField(default=12)
    total_bytes = models.CharField(max_length=50, default='1.4 GB')
    error_message = models.TextField(blank=True, null=True)
    logs = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class EvidenceSpatialPoint(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='spatial_points', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=True, null=True)
    beacon_code = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    layer_type = models.CharField(max_length=50, default='GNSS_RTK_BEACON')
    lat = models.FloatField(default=6.4281)
    lng = models.FloatField(default=3.4219)
    elevation_m = models.FloatField(default=4.2)
    accuracy_mm = models.FloatField(default=1.8)
    deviation_mm = models.FloatField(default=0.0)
    severity = models.CharField(max_length=50, default='NORMAL')
    structural_element_name = models.CharField(max_length=255, blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now)


class DeviceReportRecord(models.Model):
    id = models.CharField(max_length=100, primary_key=True, default=uuid.uuid4)
    report_reference = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=255)
    device_type = models.CharField(max_length=50, default='PUNDIT')
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE, related_name='device_reports', null=True, blank=True)
    project_id_str = models.CharField(max_length=100, blank=True, null=True)
    project_name = models.CharField(max_length=255, default='Project')
    element_id = models.CharField(max_length=100, blank=True, null=True)
    element_name = models.CharField(max_length=255, blank=True, null=True)
    report_type = models.CharField(max_length=100, default='Ultrasonic Pulse Velocity (UPV) QA/QC Report')
    standards_cited = models.JSONField(default=list, blank=True)
    compliance_status = models.CharField(max_length=50, default='COMPLIANT')
    executive_summary = models.TextField(blank=True, default='')
    metrics = models.JSONField(default=dict, blank=True)
    generated_by = models.CharField(max_length=255, default='Nexucon AI Automated Compliance Engine')
    certified_engineer = models.CharField(max_length=255, default='Engr. T. Oladipo, FNSE, COREN Reg.')
    stamped_at = models.DateTimeField(default=timezone.now)
    file_size = models.CharField(max_length=50, default='2.4 MB')
    download_url = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
