# Generated by Django 5.1.15 on 2026-08-20 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Structural Deviation Model'", max_length=150)),
                ('task_type', models.CharField(choices=[('structural_deviation', 'Structural Deviation'), ('thermal_anomaly', 'Thermal Anomaly'), ('rebar_detection', 'Rebar Detection'), ('clash_detection', 'Clash Detection'), ('progress_validation', 'Progress Validation')], max_length=50)),
                ('version', models.CharField(help_text='e.g. v2.4.1', max_length=50)),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. gemini, local-cnn', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='healthy', max_length=20)),
                ('cpu_utilization', models.FloatField(blank=True, help_text='Percent 0-100', null=True)),
                ('gpu_utilization', models.FloatField(blank=True, help_text='Percent 0-100, reported by the worker', null=True)),
                ('memory_used_gb', models.FloatField(blank=True, null=True)),
                ('memory_total_gb', models.FloatField(blank=True, null=True)),
                ('gpu_workers', models.IntegerField(blank=True, help_text='Allocated GPU worker processes', null=True)),
                ('is_api_host', models.BooleanField(default=False, help_text='True for the node serving this API')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
