# Generated by Django 5.2 on 2026-08-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_type_notification_metadata_and_more'),
        ('notifications', '0003_inappnotification_webhookdelivery'),
    ]

    operations = [
    ]
